name: catcher
description: Plugin for error catching. Allows handling errors when they're not catched by developer. Plugin provides multiple handlers for errors.
version: 0.2.7
author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/catcher

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info: ^0.4.0+3
  package_info: ^0.4.0+6
  mailer: ^3.0.3
  dio: ^3.0.3
  flutter_mailer: ^0.4.1+2
  logging: ^0.11.3+2

